<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
		'login/process',
		array(
				'action'     => 'authenticate',
		)
));
// $form->prepare();

// echo $this->form()->openTag($form);
// echo $this->formCollection($form);
// echo $this->form()->closeTag();

if ($this->messages){
	echo '<ul>';
	foreach($this->messages as $message)
	{
		echo '<li>'.$message.'</li>';
	}
	echo '</ul>';
}
?>
<div class="modal-dialog">
<div class="modal-content">
        <?php echo $this->form()->openTag($form); ?>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Authentification sur MonAlbum.fr</h4>
            <?php echo $this->flashMessenger()->render('error', array('alert', 'alert-danger'));?>
            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
        </div>
        <div class="modal-body">
            <p>
                <?php echo $this->formLabel($form->get('username'));
                echo $this->formElement($form->get('username'));
                echo $this->formElementErrors($form->get('username'));?>
            </p>
            <p>
                <?php echo $this->formLabel($form->get('password'));
                echo $this->formElement($form->get('password'));
                echo $this->formElementErrors($form->get('password'));?>
            </p>
            <p>
                <?php echo $this->formLabel($form->get('rememberme'));
                echo $this->formElement($form->get('rememberme'));
                echo $this->formElementErrors($form->get('rememberme'));?>
            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            <button type="submit" class="btn btn-primary">Je m'identifie</button>
        </div>
    <?php echo $this->form()->closeTag(); ?>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->